#pragma once

/*
LOG_LEVEL
   LOG_LEVEL_TRACE
   LOG_LEVEL_DEBUG
   LOG_LEVEL_INFO
   LOG_LEVEL_WARN
   LOG_LEVEL_ERROR
   LOG_LEVEL_DISABLE

LOG_LEVEL_TEXT_FORMAT
   LOG_LEVEL_TEXT_FORMAT_LETTER
   LOG_LEVEL_TEXT_FORMAT_SHORT
   LOG_LEVEL_TEXT_FORMAT_FULL

LOG_TIME
   LOG_TIME_DISABLE
   LOG_TIME_MICROS
   LOG_TIME_MILLIS
   LOG_TIME_HHMMSSMS
   LOG_TIME_HHHHMMSSMS
   LOG_TIME_LOCALTIME

LOG_FILENAME
   LOG_FILENAME_DISABLE
   LOG_FILENAME_ENABLE
   LOG_FILENAME_LINENUMBER_ENABLE
   LOG_FILENAME_LINENUMBER_FUNCTION_ENABLE

LOG_COLOR
   LOG_COLOR_DISABLE
   LOG_COLOR_ENABLE
*/

#define LOG_LEVEL LOG_LEVEL_TRACE

#define LOG_LEVEL_TEXT_FORMAT LOG_LEVEL_TEXT_FORMAT_SHORT

#define LOG_STREAM Serial

void panicHandler();                   // forward declaration custom halt function
#define LOG_PANIC_HANDLER panicHandler // set custom panic handler at compile time

#define LOG_ASSERT_ENABLE 1

#include <FormatLog.h>