#pragma once

// Serial logging settings
#define LOG_LEVEL LOG_LEVEL_TRACE
#define LOG_LEVEL_TEXT_FORMAT LOG_LEVEL_TEXT_FORMAT_SHORT
#define LOG_TIME LOG_TIME_MILLIS
#define LOG_FILENAME LOG_FILENAME_LINENUMBER_ENABLE
#define LOG_COLOR LOG_COLOR_DISABLE
#define LOG_STATIC_BUFFER_SIZE 256
#define LOG_STREAM Serial

// Storage settings
#define LOG_STORAGE_ENABLE 1
#define LOG_STORAGE_LEVEL LOG_LEVEL_WARN
#define LOG_STORAGE_MAX_BUFFER_MESSAGES 32
#define LOG_STORAGE_MAX_BUFFER_SIZE 4096
#define LOG_STORAGE_MAX_FILE_SIZE (1024 * 100) // 100KB per file
#define LOG_STORAGE_MAX_FILES 3

#include <FormatLog.h>
